#include<stdio.h>
#include<stdlib.h>
#include<time.h>

int BuscaPrimeiraOcorrencia(int num, int vet4[])
{
    int i=0;
    while(vet4[i]!=num)
    {
        i++;
    }
    return i;
}

main()
{
    clock_t ini,end;
    ini=clock();
    float decor;
    int vet1[11]={1,2,3,4,5,6,7,8,9,10,11};
    int vet2[21]={11,22,33,44,55,56,57,58,59,60,21,22,33,12,77,88,10,200,234,100,102};
    int vet3[42]={1,2,3,4,5,6,7,8,9,10,11,59,60,21,22,33,12,77,88,100,11,22,33,44,55,
                  56,57,58,26,33,102,108,110,222,333,123,321,222,333,111,10,07};
    int conf;
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet1);
printf("Vet1: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(22,vet2);
printf("Vet2: O elemento procurado esta na %da posicao\n",conf+1);
conf=BuscaPrimeiraOcorrencia(2,vet3);
printf("Vet3: O elemento procurado esta na %da posicao\n",conf+1);
end=clock();
decor=(end-ini)/(CLOCKS_PER_SEC / 1000);
printf("Tempo gasto:%.2f\n",decor);
getchar();
getchar();
}
